# Generated by Django 5.1.3 on 2024-11-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='time_spent',
            field=models.FloatField(),
        ),
    ]
